spring.application.name=restapi

spring.datasource.url=jdbc:postgresql://postgres-db:5432/togezzer
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.try-it-out-enabled=true

# RabbitMQ (messages)
togezzer.rabbitmq.message-exchange=message.exchange
togezzer.rabbitmq.queue.chat-sauvegarde=queue-message-chat-sauvegarde
togezzer.rabbitmq.queue.live-chat-service=queue-message-live-chat-service
togezzer.rabbitmq.routing-key.chat-sauvegarde=routing-message-chat-sauvegarde
togezzer.rabbitmq.routing-key.live-chat-service=routing-message-live-chat-service

# Base URL pour appeler l'autre service (utilisé par MessageApiClientService)
togezzer.chat-sauvegarde.base-url=http://localhost:8080
